<?php

/**
 * @file
 * Provides the SSO functionality for client sites.
 */

/**
 * Implements hook_init().
 *
 * Start the OAuth2 login flow for an anonymous user if:
 * - they hit the 'user', 'user/login' or 'user/password' URL, unless ?admin
 *   is present in the URL.
 * - they have the login cookie (indicating that they have logged into another
 *   site in the network).
 */
function openid_connect_sso_client_init() {
  $anon = user_is_anonymous();
  $on_user_page = in_array(request_path(), array('user', 'user/login', 'user/password'));
  $new_login = $anon && $on_user_page && !isset($_GET['admin']);
  $has_cookie = isset($_COOKIE['Drupal_visitor_SSOLogin']);
  // The session param indicates that an OAuth2 flow was already started,
  // and the server has just redirected the user back to the redirect callback.
  $has_session_param = isset($_SESSION['openid_connect_state']);
  $network_login = $has_cookie && !$has_session_param;
  if ($network_login && !$anon) {
    // We're supposed to log the user in, but he's already logged in.
    // Destroy his current session and log him out first.
    // This code is the same as user_logout(), but without the redirect.
    watchdog('user', 'Session closed for %name.', array('%name' => $user->name));
    module_invoke_all('user_logout', $user);
    session_destroy();
  }

  if ($new_login || $network_login) {
    $_SESSION['openid_connect_destination'] = $on_user_page ? '<front>' : request_path();
    $client = openid_connect_get_client('generic');
    $scopes = openid_connect_get_scopes();
    $client->authorize($scopes);
  }
}

/**
 * Implements hook_menu_alter().
 */
function openid_connect_sso_client_menu_alter(&$items) {
  // Don't allow users to edit their accounts, that needs to happen
  // on the server.
  $items['user/%user/edit']['access callback'] = 'user_access';
  $items['user/%user/edit']['access arguments'] = array('administer users');
}
